
inicio
	real num1, num2, subt
      
      escrever "Introduz dois números. \n"
      
      ler num1, num2
      
      
      se num1 > num2 entao
      
          subt <- num1 - num2
          escrever "A diferença entre os dois números é de ", troca, ". \n" 
      fimse 
     
      se num1 < num2 entao
      
          troca <- num2 - num1
          escrever "A diferença entre os dois números é de ", troca, ". \n" 
      fimse 
fim
