
inicio
	inteiro num1, num2, num3, quadrado1, quadrado2, quadrado3, soma
      escrever "Introduza três números: \n"
      ler num1, num2, num3
      
      quadrado1 <- num1 ^ 2
      quadrado2 <- num2 ^ 2
      quadrado3 <- num3 ^ 2
      escrever "O quadrado dos três números é ", quadrado1, ",", quadrado2, " e ", quadrado3, ". \n"
      
      soma <- quadrado1 + quadrado2 + quadrado1
      escrever "A soma dos quadrados dos três números é ", soma, "."
      
fim
